import DocumentValue, { humanizeKey } from "./DocumentValue";
import EnrichedItemList from "./EnrichedItemList";

// These four sections carry Domain Agent enrichment markers (modified_by_domain_agent,
// original_description, origin, domain_citation) directly on their array items in a real
// Enhanced SRS -- rendered as color-coded cards (see EnrichedItemList) instead of a generic
// table, so an enrichment is visually obvious rather than buried as just another field.
const ENRICHABLE_SECTIONS = new Set([
  "functional_requirements",
  "non_functional_requirements",
  "acceptance_criteria",
  "validation_rules",
]);

// SRS and Enhanced SRS share an identical shape (confirmed against real generated artifacts) --
// one renderer covers both. Section order follows how a human would actually read a
// requirements document: goal/scope first, requirements/stories/criteria next, technical
// expectations, then constraints/risks/traceability last.
const SECTION_ORDER = [
  ["business_goal", "Business Goal"],
  ["scope", "Scope"],
  ["out_of_scope", "Out of Scope"],
  ["user_roles", "User Roles"],
  ["user_stories", "User Stories"],
  ["functional_requirements", "Functional Requirements"],
  ["non_functional_requirements", "Non-Functional Requirements"],
  ["acceptance_criteria", "Acceptance Criteria"],
  ["input_requirements", "Input Requirements"],
  ["output_requirements", "Output Requirements"],
  ["ui_expectations", "UI Expectations"],
  ["api_expectations", "API Expectations"],
  ["data_requirements", "Data Requirements"],
  ["validation_rules", "Validation Rules"],
  ["domain_enrichment_metadata", "Domain Enrichment"],
  ["constraints", "Constraints"],
  ["assumptions", "Assumptions"],
  ["risks", "Risks"],
  ["dependencies", "Dependencies"],
  ["traceability", "Traceability"],
];

const HEADER_FIELDS = ["feature_name", "project_name", "target_stack", "architectural_style", "project_type"];

function Section({ sectionKey, title, value }) {
  if (value === null || value === undefined || (Array.isArray(value) && value.length === 0)) return null;

  return (
    <section className="mb-5">
      <h3 className="text-sm font-bold text-gray-900 dark:text-gray-100 uppercase tracking-wide mb-1.5 pb-1 border-b border-gray-100 dark:border-gray-800">
        {title}
      </h3>
      {ENRICHABLE_SECTIONS.has(sectionKey) ? <EnrichedItemList items={value} /> : <DocumentValue value={value} />}
    </section>
  );
}

const DOCUMENT_TYPE_LABELS = {
  srs: "Software Requirements Specification (SRS)",
  enhanced_srs: "Enhanced Software Requirements Specification (Enhanced SRS)",
  srs_preview: "SRS Preview (In Progress)",
};

export default function SrsDocumentViewer({ data, artifactType }) {
  if (!data) return null;

  const knownKeys = new Set([...SECTION_ORDER.map(([k]) => k), ...HEADER_FIELDS, "project_id", "feature_id"]);
  const extraKeys = Object.keys(data).filter((k) => !knownKeys.has(k));

  return (
    <div className="max-w-3xl">
      <div className="mb-5 pb-3 border-b border-gray-200 dark:border-gray-800">
        <p className="text-xs font-bold text-accent-600 dark:text-accent-400 uppercase tracking-wide mb-1">
          {DOCUMENT_TYPE_LABELS[artifactType] || "Software Requirements Specification (SRS)"}
        </p>
        <h2 className="text-lg font-bold text-gray-900 dark:text-gray-100">{data.feature_name || "Untitled Feature"}</h2>
        <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
          {[data.project_name, data.project_type, data.target_stack, data.architectural_style].filter(Boolean).join(" · ")}
        </p>
      </div>

      {SECTION_ORDER.map(([key, title]) => (
        <Section key={key} sectionKey={key} title={title} value={data[key]} />
      ))}

      {/* Nothing generated by the agent is ever silently hidden: any field this component
          doesn't explicitly know about still renders, generically, at the end. */}
      {extraKeys.map((key) => (
        <Section key={key} sectionKey={key} title={humanizeKey(key)} value={data[key]} />
      ))}
    </div>
  );
}
