"""
Architecture Agent SDS Markdown Builder.

Purpose:
This file converts Architecture Agent SDS JSON into human-readable Markdown.

Why this file exists:
- The LLM generates JSON only.
- Markdown is generated safely by backend code.
- This avoids JSON parsing problems.
- This keeps SDS formatting inside Architecture Agent only.
"""

from typing import Any


class ArchitectureSDSMarkdownBuilder:
    """
    Converts SDS JSON into SDS Markdown.

    This class is specific to Architecture Agent.
    Other agents should not depend on this class.
    """

    def build(self, sds_json: dict[str, Any]) -> str:
        """
        Build full SDS Markdown document from SDS JSON.
        """

        return f"""# Software Design Specification: {sds_json.get("feature_name", "Untitled Feature")}

## 1. Project Information

- **Project ID:** {sds_json.get("project_id", "N/A")}
- **Project Name:** {sds_json.get("project_name", "N/A")}
- **Project Type:** {sds_json.get("project_type", "N/A")}
- **Feature ID:** {sds_json.get("feature_id", "N/A")}
- **Feature Name:** {sds_json.get("feature_name", "N/A")}
- **Target Stack:** {sds_json.get("target_stack", "MERN")}
- **Architecture Style:** {sds_json.get("architecture_style", "modular")}

---

## 2. Feature Design Overview

{sds_json.get("feature_design_overview", "Not specified.")}

---

## 3. Frontend Responsibilities

{self._simple_list(sds_json.get("frontend_responsibilities", []))}

---

## 4. Backend Responsibilities

{self._simple_list(sds_json.get("backend_responsibilities", []))}

---

## 5. Database Design

{self._database_design(sds_json.get("database_design", {}))}

---

## 6. API Design Summary

{self._api_summary(sds_json.get("api_design_summary", []))}

> Note: This is only an SDS-level API design summary. The Architecture Agent is not generating a separate API contract artifact in this implementation.

---

## 7. Data Flow

{self._simple_list(sds_json.get("data_flow", []))}

---

## 8. Error Handling Design

{self._simple_list(sds_json.get("error_handling_design", []))}

---

## 9. Authentication and Authorization Design

{self._simple_list(sds_json.get("authentication_authorization_design", []))}

---

## 10. Folder Structure Suggestion

{self._simple_list(sds_json.get("folder_structure_suggestion", []))}

---

## 11. Dependency List

{self._simple_list(sds_json.get("dependency_list", []))}

---

## 12. Integration With Previous Features

{self._simple_list(sds_json.get("integration_with_previous_features", []))}

---

## 13. Scalability Notes

{self._simple_list(sds_json.get("scalability_notes", []))}

---

## 14. Assumptions

{self._simple_list(sds_json.get("assumptions", []))}

---

## 15. Constraints

{self._simple_list(sds_json.get("constraints", []))}

---

## 16. Traceability to Requirements

{self._traceability(sds_json.get("traceability", []))}

---

## 17. Human Approval Note

This SDS was generated by the Architecture Agent.

A human reviewer must approve this artifact before it is passed to the UI/UX Agent.
"""

    def _simple_list(self, items: list[Any]) -> str:
        """
        Convert a list into Markdown bullets.
        """

        if not items:
            return "- Not specified."

        return "\n".join(f"- {item}" for item in items)

    def _database_design(self, database_design: dict[str, Any]) -> str:
        """
        Convert database design object into Markdown.
        """

        if not database_design:
            return "- Not specified."

        lines = []

        collections = database_design.get("collections", [])
        data_notes = database_design.get("data_notes", [])

        lines.append("### Collections")
        lines.append(self._simple_list(collections))

        lines.append("\n### Data Notes")
        lines.append(self._simple_list(data_notes))

        return "\n".join(lines)

    def _api_summary(self, endpoints: list[dict[str, Any]]) -> str:
        """
        Convert SDS-level API design summary into Markdown.

        This is not an API contract.
        It is only design-level documentation.
        """

        if not endpoints:
            return "- Not specified."

        lines = []

        for endpoint in endpoints:
            method = endpoint.get("method", "METHOD")
            path = endpoint.get("endpoint", "/path")
            purpose = endpoint.get("purpose", "No purpose provided.")
            related = endpoint.get("related_requirements", [])

            related_text = ", ".join(related) if isinstance(related, list) else str(related)

            lines.append(f"- **{method} {path}**")
            lines.append(f"  - Purpose: {purpose}")
            lines.append(f"  - Related Requirements: {related_text or 'N/A'}")

        return "\n".join(lines)

    def _traceability(self, items: list[dict[str, Any]]) -> str:
        """
        Convert traceability records into Markdown.
        """

        if not items:
            return "- Not specified."

        lines = []

        for item in items:
            requirement_id = item.get("requirement_id", "N/A")
            sds_section = item.get("sds_section", "N/A")
            decision = item.get("design_decision", "N/A")

            lines.append(f"- **{requirement_id}** → {sds_section}")
            lines.append(f"  - Design Decision: {decision}")

        return "\n".join(lines)