# """
# Architecture Agent internal schemas.

# These schemas are used inside the Architecture Agent only.

# They are different from API schemas.
# API schemas are in:
#     app/schemas/architecture_schema.py
# """

# from pydantic import BaseModel


# class ArchitectureAgentInput(BaseModel):
#     """
#     Internal input passed to Architecture Agent.

#     project:
#         Project metadata from database.

#     feature:
#         Feature metadata from database.

#     srs_json:
#         Approved SRS JSON from Requirement Agent.

#     enhanced_srs_json:
#         Approved Enhanced SRS JSON from Domain Agent if available.
#         For now, this can be None because Domain Agent may not be implemented yet.

#     architecture_notes:
#         Optional instruction from human.

#     human_comment:
#         Optional user comment.
#     """

#     project: dict
#     feature: dict
#     srs_json: dict
#     enhanced_srs_json: dict | None = None
#     architecture_notes: str | None = None
#     human_comment: str | None = None


# class ArchitectureAgentOutput(BaseModel):
#     """
#     Internal output produced by Architecture Agent.

#     sds_json:
#         Machine-readable Software Design Specification.

#     sds_markdown:
#         Human-readable SDS generated by architecture markdown builder.

#     usecase_json:
#         Structured use case diagram data.

#     usecase_puml:
#         PlantUML source generated from usecase_json.

#     raw_llm_output:
#         Original LLM output for debugging.
#     """

#     sds_json: dict
#     sds_markdown: str
#     usecase_json: dict
#     usecase_puml: str
#     raw_llm_output: str


"""
Architecture Agent internal schemas.

These schemas are used inside the Architecture Agent only.

Important:
The API request schema is in:
    app/schemas/architecture_schema.py

This file is only for internal Architecture Agent input/output handling.
"""

from pydantic import BaseModel


class ArchitectureAgentInput(BaseModel):
    """
    Internal input passed to Architecture Agent.

    project:
        Project metadata from database.

    feature:
        Feature metadata from database.

    srs_json:
        Approved SRS JSON from Requirement Agent.

    enhanced_srs_json:
        Approved Enhanced SRS JSON from Domain Agent if available.
        This can be None.

    architecture_notes:
        Optional user instruction for architecture generation.

    human_comment:
        Optional user comment.
    """

    project: dict
    feature: dict
    srs_json: dict
    enhanced_srs_json: dict | None = None
    architecture_notes: str | None = None
    human_comment: str | None = None


class ArchitectureAgentOutput(BaseModel):
    """
    Internal output produced by Architecture Agent.

    sds_json:
        Machine-readable Software Design Specification.

    sds_markdown:
        Human-readable SDS generated from sds_json.

    usecase_analysis_json:
        Intermediate analysis used to create a better UML use case diagram.
        This helps prevent simple diagrams like:
            Customer -> Use Login Feature

    usecase_json:
        Structured use case diagram model.

    usecase_puml:
        PlantUML source generated from usecase_json.

    raw_llm_output:
        Original LLM output for debugging.
    """

    sds_json: dict
    sds_markdown: str
    usecase_analysis_json: dict
    usecase_json: dict
    usecase_puml: str
    raw_llm_output: str