# """
# Architecture Agent Use Case Diagram Builder.

# Purpose:
# This file converts structured usecase_json into PlantUML source.

# Why this file exists:
# - The LLM should not directly generate PlantUML.
# - LLM-generated PlantUML can easily break.
# - The backend can generate cleaner and more standard PlantUML from JSON.
# - This keeps diagram generation specific to Architecture Agent.

# Use Case Diagram Standards Applied:
# - Actors are outside the system boundary.
# - Use cases are inside the system boundary.
# - Actor-to-use-case association is a solid line.
# - <<include>> is used only for mandatory reusable behavior.
# - <<extend>> is used only for optional or conditional behavior.
# - Generalization is used only for is-a relationships.
# """

# import re
# from typing import Any


# class ArchitectureUseCasePlantUMLBuilder:
#     """
#     Converts usecase_json into PlantUML use case diagram source.
#     """

#     def build(self, usecase_json: dict[str, Any]) -> str:
#         """
#         Build PlantUML source from usecase_json.
#         """

#         diagram_title = usecase_json.get("diagram_title", "Use Case Diagram")
#         system_boundary = usecase_json.get("system_boundary", "Feature System")

#         actors = usecase_json.get("actors", [])
#         use_cases = usecase_json.get("use_cases", [])
#         relationships = usecase_json.get("relationships", [])

#         lines: list[str] = []

#         lines.append("@startuml")
#         lines.append("' Auto-generated by AutoForge Architecture Agent")
#         lines.append("' Diagram type: UML Use Case Diagram")
#         lines.append("' Standards:")
#         lines.append("' - Actors are outside the system boundary")
#         lines.append("' - Use cases are inside the system boundary")
#         lines.append("' - Associations do not use arrowheads")
#         lines.append("' - <<include>> means mandatory reused behavior")
#         lines.append("' - <<extend>> means optional or conditional behavior")
#         lines.append("")
#         lines.append("left to right direction")
#         lines.append("skinparam packageStyle rectangle")
#         lines.append("skinparam shadowing false")
#         lines.append("")
#         lines.append(f"title {self._safe_label(diagram_title)}")
#         lines.append("")

#         # Actors must be outside the system boundary.
#         for actor in actors:
#             actor_id = self._safe_alias(actor.get("id", actor.get("name", "ACT")))
#             actor_name = self._safe_label(actor.get("name", actor_id))
#             lines.append(f'actor "{actor_name}" as {actor_id}')

#         lines.append("")
#         lines.append(f'rectangle "{self._safe_label(system_boundary)}" {{')

#         # Use cases are inside the system boundary.
#         for use_case in use_cases:
#             uc_id = self._safe_alias(use_case.get("id", use_case.get("name", "UC")))
#             uc_name = self._safe_label(use_case.get("name", uc_id))
#             lines.append(f'  usecase "{uc_name}" as {uc_id}')

#         lines.append("}")
#         lines.append("")

#         # Relationships are outside the boundary block.
#         for relationship in relationships:
#             relation_line = self._build_relationship(relationship)

#             if relation_line:
#                 lines.append(relation_line)

#         lines.append("")
#         lines.append("@enduml")

#         return "\n".join(lines)

#     def _build_relationship(self, relationship: dict[str, Any]) -> str | None:
#         """
#         Convert one relationship object into PlantUML syntax.

#         Supported relationship types:
#         - association
#         - include
#         - extend
#         - generalization
#         """

#         source = self._safe_alias(relationship.get("from", ""))
#         target = self._safe_alias(relationship.get("to", ""))
#         relation_type = relationship.get("type", "association").lower()
#         label = relationship.get("label", "")

#         if not source or not target:
#             return None

#         if relation_type == "association":
#             # UML use case actor association uses a plain solid line.
#             if label:
#                 return f"{source} -- {target} : {self._safe_label(label)}"
#             return f"{source} -- {target}"

#         if relation_type == "include":
#             # Base use case points to included use case.
#             return f"{source} .> {target} : <<include>>"

#         if relation_type == "extend":
#             # Extending use case points to base use case.
#             return f"{source} .> {target} : <<extend>>"

#         if relation_type == "generalization":
#             # Child points to parent.
#             return f"{source} --|> {target}"

#         # Unknown relationship types are ignored to avoid invalid PlantUML.
#         return None

#     def _safe_alias(self, value: str) -> str:
#         """
#         Convert actor/use case ID into safe PlantUML alias.

#         Example:
#             ACT-001 -> ACT_001
#             UC-LOGIN -> UC_LOGIN
#         """

#         value = str(value).strip()
#         value = re.sub(r"[^a-zA-Z0-9_]", "_", value)

#         if not value:
#             value = "UNKNOWN"

#         if value[0].isdigit():
#             value = f"ID_{value}"

#         return value

#     def _safe_label(self, value: str) -> str:
#         """
#         Escape quotes from labels to avoid PlantUML syntax errors.
#         """

#         return str(value).replace('"', "'").strip()

"""
Architecture Agent Use Case Diagram Builder.

Purpose:
This file converts structured usecase_json into PlantUML source.

Why:
The LLM should not directly write PlantUML.
The LLM produces structured JSON.
Backend converts that JSON into clean PlantUML.

This gives us:
- safer syntax
- better control
- consistent UML standards
- easier validation
"""

import re
from typing import Any


class ArchitectureUseCasePlantUMLBuilder:
    """
    Converts usecase_json into PlantUML use case diagram source.
    """

    def build(self, usecase_json: dict[str, Any]) -> str:
        """
        Build PlantUML source from usecase_json.
        """

        diagram_title = usecase_json.get("diagram_title", "Use Case Diagram")
        system_boundary = usecase_json.get("system_boundary", "Feature System")

        actors = usecase_json.get("actors", [])
        use_cases = usecase_json.get("use_cases", [])
        relationships = usecase_json.get("relationships", [])
        notes = usecase_json.get("notes", [])

        lines: list[str] = []

        lines.append("@startuml")
        lines.append("' Auto-generated by AutoForge Architecture Agent")
        lines.append("' Diagram type: UML Use Case Diagram")
        lines.append("' Actors are outside system boundary")
        lines.append("' Use cases are inside system boundary")
        lines.append("' <<include>> = mandatory reused behaviour")
        lines.append("' <<extend>> = optional, alternative, or error behaviour")
        lines.append("")
        lines.append("left to right direction")
        lines.append("skinparam packageStyle rectangle")
        lines.append("skinparam shadowing false")
        lines.append("skinparam usecase {")
        lines.append("  BackgroundColor #FFFFFF")
        lines.append("  BorderColor #222222")
        lines.append("}")
        lines.append("")
        lines.append(f"title {self._safe_label(diagram_title)}")
        lines.append("")

        # Actors are outside the system boundary.
        for actor in actors:
            actor_id = self._safe_alias(actor.get("id", actor.get("name", "ACT")))
            actor_name = self._safe_label(actor.get("name", actor_id))
            lines.append(f'actor "{actor_name}" as {actor_id}')

        lines.append("")

        # Use cases are inside the system boundary.
        lines.append(f'rectangle "{self._safe_label(system_boundary)}" {{')

        for use_case in use_cases:
            uc_id = self._safe_alias(use_case.get("id", use_case.get("name", "UC")))
            uc_name = self._safe_label(use_case.get("name", uc_id))
            lines.append(f'  usecase "{uc_name}" as {uc_id}')

        lines.append("}")
        lines.append("")

        # Relationships are outside the rectangle block.
        for relationship in relationships:
            relation_line = self._build_relationship(relationship)

            if relation_line:
                lines.append(relation_line)

        lines.append("")

        # Notes are useful for constraints, NFRs, risks, and security rules.
        for note in notes:
            note_lines = self._build_note(note)

            if note_lines:
                lines.extend(note_lines)
                lines.append("")

        lines.append("@enduml")

        return "\n".join(lines)

    def _build_relationship(self, relationship: dict[str, Any]) -> str | None:
        """
        Convert one relationship object into PlantUML syntax.

        Supported relationship types:
        - association
        - include
        - extend
        - generalization
        """

        source = self._safe_alias(relationship.get("from", ""))
        target = self._safe_alias(relationship.get("to", ""))
        relation_type = str(relationship.get("type", "association")).lower()
        label = relationship.get("label", "")

        if not source or not target:
            return None

        if relation_type == "association":
            if label:
                return f"{source} -- {target} : {self._safe_label(label)}"
            return f"{source} -- {target}"

        if relation_type == "include":
            # Base use case points to included use case.
            return f"{source} .> {target} : <<include>>"

        if relation_type == "extend":
            # Extension use case points to base use case.
            return f"{source} .> {target} : <<extend>>"

        if relation_type == "generalization":
            # Child points to parent.
            return f"{source} --|> {target}"

        return None

    def _build_note(self, note: dict[str, Any]) -> list[str]:
        """
        Build PlantUML note.

        Notes are used for:
        - constraints
        - non-functional requirements
        - security rules
        - risks
        - architectural rules
        """

        target = self._safe_alias(note.get("target", ""))
        title = self._safe_label(note.get("title", "Note"))
        description = self._safe_label(note.get("description", ""))

        if not target or not description:
            return []

        lines = []
        lines.append(f"note right of {target}")
        lines.append(f"  {title}")
        lines.append(f"  {description}")
        lines.append("end note")

        return lines

    def _safe_alias(self, value: str) -> str:
        """
        Convert actor/use case ID into safe PlantUML alias.

        Example:
            ACT-001 -> ACT_001
            UC-LOGIN -> UC_LOGIN
        """

        value = str(value).strip()
        value = re.sub(r"[^a-zA-Z0-9_]", "_", value)

        if not value:
            value = "UNKNOWN"

        if value[0].isdigit():
            value = f"ID_{value}"

        return value

    def _safe_label(self, value: str) -> str:
        """
        Escape unsafe characters from labels.
        """

        return str(value).replace('"', "'").strip()