"""
Artifact schemas.

Artifacts are the main outputs generated by agents.

Examples:
- SRS Markdown
- SRS JSON
- Enhanced SRS
- SDS
- Use case diagram
- UI HTML
- Generated code manifest
- Deployment logs
"""

from datetime import datetime
from pydantic import BaseModel
from app.core.enums import AgentName, ArtifactType, ArtifactFormat, ApprovalStatus


class ArtifactCreateRequest(BaseModel):
    """
    Internal request model for creating an artifact record.
    """
    project_id: str
    feature_id: str
    agent_name: AgentName
    artifact_type: ArtifactType
    artifact_format: ArtifactFormat
    file_path: str
    version: int = 1


class ArtifactResponse(BaseModel):
    """
    API response for artifact metadata.
    """
    artifact_id: str
    project_id: str
    feature_id: str
    agent_name: AgentName
    artifact_type: ArtifactType
    artifact_format: ArtifactFormat
    file_path: str
    version: int
    approval_status: ApprovalStatus
    created_at: datetime