"""
Artifact schemas.

Artifacts are the main outputs generated by agents.

Examples:
- SRS Markdown
- SRS JSON
- Enhanced SRS
- SDS
- Use case diagram
- UI HTML
- Generated code manifest
- Deployment logs
"""

from datetime import datetime
from pydantic import BaseModel
from app.core.enums import AgentName, ArtifactType, ArtifactFormat, ApprovalStatus


class ArtifactCreateRequest(BaseModel):
    """
    Internal request model for creating an artifact record.
    """
    project_id: str
    feature_id: str
    agent_name: AgentName
    artifact_type: ArtifactType
    artifact_format: ArtifactFormat
    file_path: str
    version: int = 1


class ArtifactResponse(BaseModel):
    """
    API response for artifact metadata.
    """
    artifact_id: str
    project_id: str
    feature_id: str
    agent_name: AgentName
    artifact_type: ArtifactType
    artifact_format: ArtifactFormat
    file_path: str
    version: int
    approval_status: ApprovalStatus
    created_at: datetime
    # Computed from the file on disk at read time (not stored) -- None if the file is missing.
    # Purely cosmetic (shown next to each artifact in the frontend), never used for any decision.
    size_bytes: int | None = None
    # A short human-readable description of what this artifact's content actually says (e.g. a
    # CODE_PLAN artifact's own "summary" field) -- optional, stored alongside the artifact record.
    # Lets the frontend chat surface real, model-generated text instead of a generic
    # "Produced X (vN)" placeholder. None for artifact types that don't set one.
    summary: str | None = None